### ISSUE TITLE
[NOTE] *How To* solve "Cannot find module '../run-schematic/executor'"

### ISSUE THREAD

**Issue by NathanWalker** [nstudio/xplat#144]
If you encounter the following error when using `nx generate app` or any generator:
```
Cannot find module '../run-schematic/executor'
```
This is likely due to nested node_modules installed into a dependency.
To solve delete the `node_modules` and `package-lock.json` and rerun `npm install`.

The generators should now work as expected.

**Comment by NathanWalker** [comment]
@numerical25 when you get a chance could you reference a few commands you tried and which you had trouble with here?

**Comment by Cselt** [comment]
I get this error when I try to create a new workspace.

```
npx create-xplat-workspace myworkspace
npx: installed 53 in 5.436s                                                                                             
px --ignore-existing create-nx-workspace@latest xplat-test
npx: installed 164 in 21.661s                                                                                           
? What to create in the new workspace empty             [an empty workspace]                                            
? CLI to power the Nx workspace       Nx           [Extensible CLI for JavaScript and TypeScript applications]          
Creating a sandbox with Nx...                                                                                           [#############################################################################################################] 315/315 
new xplat-test --preset="empty" --collection=@nrwl/workspace                                                            
[#############################################################################################################] 473/473 
warning: LF will be replaced by CRLF in .editorconfig.                                                                  
The file will have its original line endings in your working directory.                                                 
warning: LF will be replaced by CRLF in .gitignore.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in .prettierignore.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in .prettierrc.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in .vscode/extensions.json.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in README.md.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in apps/.gitkeep.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in nx.json.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in package.json.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in tools/tsconfig.tools.json.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in tsconfig.json.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in workspace.json.
The file will have its original line endings in your working directory.
    Successfully initialized git.
CREATE xplat-test/nx.json (203 bytes)                                                                                   
CREATE xplat-test/tsconfig.json (509 bytes)                                                                             
CREATE xplat-test/package.json (1069 bytes)                                                                             
CREATE xplat-test/README.md (2542 bytes)                                                                                
CREATE xplat-test/.editorconfig (245 bytes)                                                                             
CREATE xplat-test/.gitignore (503 bytes)                                                                                
CREATE xplat-test/.prettierignore (74 bytes)                                                                            
CREATE xplat-test/.prettierrc (26 bytes)                                                                                
CREATE xplat-test/workspace.json (864 bytes)                                                                           
CREATE xplat-test/apps/.gitkeep (1 bytes)                                                                               
CREATE xplat-test/libs/.gitkeep (0 bytes)                                                                               
CREATE xplat-test/tools/tsconfig.tools.json (218 bytes)                                                                 
CREATE xplat-test/tools/schematics/.gitkeep (0 bytes)                                                                   
CREATE xplat-test/.vscode/extensions.json (109 bytes)                                                                   
npm install -D @nstudio/xplat
npm WARN rm not removing D:\Workspace\xplat-test\node_modules\.bin\semver.cmd as it wasn't installed by D:\Workspace\xplat-test\node_modules\semver
npm WARN rm not removing D:\Workspace\xplat-test\node_modules\.bin\semver as it wasn't installed by D:\Workspace\xplat-test\node_modules\semver
                                                                                                                        
> @nstudio/xplat@8.0.6 postinstall D:\Workspace\xplat-test\node_modules\@nstudio\xplat
> node src/utils/postinstall.js

An issue were detected during patching the nx-formatter Error: Apply couldn't patch for nx format
    at D:\Workspace\xplat-test\node_modules\@nstudio\xplat\src\utils\postinstall.js:139:31
    at step (D:\Workspace\xplat-test\node_modules\@nstudio\xplat\src\utils\postinstall.js:32:23)
    at Object.next (D:\Workspace\xplat-test\node_modules\@nstudio\xplat\src\utils\postinstall.js:13:53)
    at fulfilled (D:\Workspace\xplat-test\node_modules\@nstudio\xplat\src\utils\postinstall.js:4:58)

>  XPLAT  Note:                                                                                                         
  xplat is updating "D:\Workspace\xplat-test\.prettierignore" with a few important extra rules. You may double-check the contents afterwards to ensure they meet your satisfaction.

npm notice created a lockfile as package-lock.json. You should commit this file.                                        
+ @nstudio/xplat@8.0.6
added 23 packages from 70 contributors, updated 244 packages and audited 1172 packages in 96.187s
found 0 vulnerabilities                                                                                                 
npx nx g @nstudio/xplat:init
? Would you like to generate xplat supporting architecture now? You can also generate later with: nx generate @nstudio/xplat:init not right now     [just add xplat tooling]                                                                    
? Do you prefer to use a frontend framework? angular          [ensure platforms are added with Angular]                 
? Please input a 2-3 character prefix to use with xplat generators: smt                                                 
Note to VS Code users: no development mode set. xplat could not find any VS Code settings in the standard location: C:\Users\cselt\AppData\Roaming\Code\User\settings.json It's possible you don't have a user settings.json yet. If so, open VS Code User settings and save any kind of setting to have it created.                                                    
Note to VS Code users: no development mode set. xplat could not find any VS Code settings in the standard location: C:\Users\cselt\AppData\Roaming\Code\User\settings.json It's possible you don't have a user settings.json yet. If so, open VS Code User settings and save any kind of setting to have it created.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning "@nrwl/angular > jasmine-marbles@0.6.0" has unmet peer dependency "rxjs@^6.4.0".                                
warning "@nrwl/angular > @nrwl/cypress > @cypress/webpack-preprocessor@4.1.0" has unmet peer dependency "webpack@^4.18.1".
warning "@nstudio/angular > @nrwl/angular > @nrwl/cypress > fork-ts-checker-webpack-plugin@0.4.15" has unmet peer dependency "webpack@^2.3.0 || ^3.0.0 || ^4.0.0".
warning "@nstudio/angular > @nrwl/angular > @nrwl/cypress > @cypress/webpack-preprocessor > babel-loader@8.0.6" has unmet peer dependency "webpack@>=2".
warning " > @nrwl/angular@8.4.13" has incorrect peer dependency "@nrwl/workspace@8.4.13".                               
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.                                                                                      
Cannot find module '../run-schematic/executor'                                                                          
Command failed: npx nx g @nstudio/xplat:init
```

What am I doing wrong? What is the correct way to initialize an xplat workspace?

**Comment by NathanWalker** [comment]
Thanks for the report @Cselt - I believe we are going to discontinue the short binary `create-xplat-workspace` as seems to be root of issue. Try this and lemme know if better:
```
npx create-nx-workspace myworkspace

// Choose 'Empty'
// Choose 'Nx' cli when asked
```
Then add xplat to it:
```
cd myworkspace
npm i -D @nstudio/xplat
```
You should be all set at this point. `nx g app` to see all the app generator options and other generators should work. Please keep me posted and thank you for any further info.

**Comment by Cselt** [comment]
Thanks for the quick reply @NathanWalker.
I tried to generate a simple nx workspace following your recommendation and worked just fine.
I was able to add xplat to it, only encountered a postinstall error:
```
npm i -D @nstudio/xplat
npm WARN rm not removing D:\Workspace\myworkspace\node_modules\.bin\semver.cmd as it wasn't installed by D:\Workspace\myworkspace\node_modules\semver
npm WARN rm not removing D:\Workspace\myworkspace\node_modules\.bin\semver as it wasn't installed by D:\Workspace\myworkspace\node_modules\semver
                                                                                                                        																												
> @nstudio/xplat@8.0.6 postinstall D:\Workspace\myworkspace\node_modules\@nstudio\xplat
> node src/utils/postinstall.js

An issue were detected during patching the nx-formatter Error: Apply couldn't patch for nx format
    at D:\Workspace\myworkspace\node_modules\@nstudio\xplat\src\utils\postinstall.js:139:31
    at step (D:\Workspace\myworkspace\node_modules\@nstudio\xplat\src\utils\postinstall.js:32:23)
    at Object.next (D:\Workspace\myworkspace\node_modules\@nstudio\xplat\src\utils\postinstall.js:13:53)
    at fulfilled (D:\Workspace\myworkspace\node_modules\@nstudio\xplat\src\utils\postinstall.js:4:58)

>  XPLAT  Note:                                                                                                         
  xplat is updating "D:\Workspace\myworkspace\.prettierignore" with a few important extra rules. You may double-check the contents afterwards to ensure they meet your satisfaction.

npm notice created a lockfile as package-lock.json. You should commit this file.                                        
+ @nstudio/xplat@8.0.6
added 23 packages from 70 contributors, updated 244 packages and audited 1172 packages in 77.327s
found 0 vulnerabilitie
```

Then I was able to generate an Angular web application. 
```
nx g app test-app
? What type of app would like to create? web             [Web app]                                                      
? Which frontend framework should it use? angular        [Angular app]                                                  
? Use xplat supporting architecture? Yes                                                                                
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.                                                                                      
? In which directory should the app be generated?                                                                       
? Which stylesheet format would you like to use? SASS(.scss)  [ http://sass-lang.com   ]                                
Note to VS Code users: no development mode set. xplat could not find any VS Code settings in the standard location: C:\Users\cselt\AppData\Roaming\Code\User\settings.json It's possible you don't have a user settings.json yet. If so, open VS Code User settings and save any kind of setting to have it created.                                                    
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()warning "@nrwl/angular > @nrwl/cypress > @cypress/webpack-preprocessor@4.1.0" has unmet peer dependency "webpack@^4.18.1".
warning "@nstudio/angular > @nrwl/angular > @nrwl/cypress > fork-ts-checker-webpack-plugin@0.4.15" has unmet peer dependency "webpack@^2.3.0 || ^3.0.0 || ^4.0.0".
warning "@nstudio/web-angular > @nstudio/web > @nrwl/web > license-webpack-plugin@1.5.0" has unmet peer dependency "webpack-sources@>=1.0.0".
warning " > @nrwl/angular@8.4.13" has incorrect peer dependency "@nrwl/workspace@8.4.13".                               
warning "@nrwl/angular > @nrwl/cypress@8.4.13" has incorrect peer dependency "@nrwl/workspace@8.4.13".                  
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
UPDATE package.json (1306 bytes)                                                                                        
CREATE libs/core/core.module.ts (1306 bytes)                                                                            
CREATE libs/core/index.ts (166 bytes)                                                                                   
CREATE libs/core/base/base-component.ts (575 bytes)                                                                     
CREATE libs/core/base/index.ts (34 bytes)                                                                               
CREATE libs/core/environments/environment.ts (109 bytes)                                                                
CREATE libs/core/models/index.ts (42 bytes)                                                                             
CREATE libs/core/models/xplat-window.interface.ts (638 bytes)                                                           
CREATE libs/core/services/index.ts (253 bytes)                                                                          
CREATE libs/core/services/log.service.spec.ts (4409 bytes)                                                              
CREATE libs/core/services/log.service.ts (1348 bytes)                                                                   
CREATE libs/core/services/tokens.ts (409 bytes)                                                                         
CREATE libs/core/services/window.service.ts (2061 bytes)                                                                
CREATE libs/features/index.ts (22 bytes)                                                                                
CREATE libs/features/ui/index.ts (70 bytes)                                                                             
CREATE libs/features/ui/ui.module.ts (309 bytes)                                                                        
CREATE libs/features/ui/base/header.base-component.ts (468 bytes)                                                       
CREATE libs/features/ui/base/index.ts (41 bytes)                                                                        
CREATE libs/features/ui/pipes/date-order.pipe.ts (513 bytes)                                                            
CREATE libs/features/ui/pipes/index.ts (93 bytes)                                                                       
CREATE libs/utils/angular.ts (225 bytes)                                                                                
CREATE libs/utils/index.ts (82 bytes)                                                                                   
CREATE libs/utils/objects.ts (172 bytes)                                                                                
CREATE libs/utils/platform.ts (699 bytes)                                                                               
CREATE libs/scss/package.json (56 bytes)                                                                                
CREATE libs/scss/_index.scss (166 bytes)                                                                                
CREATE libs/scss/_variables.scss (219 bytes)                                                                            
CREATE xplat/web/index.ts (52 bytes)                                                                                    
CREATE xplat/web/.xplatframework (7 bytes)                                                                              
CREATE xplat/web/core/core.module.spec.ts (195 bytes)                                                                   
CREATE xplat/web/core/core.module.ts (1585 bytes)                                                                       
CREATE xplat/web/core/index.ts (79 bytes)                                                                               
CREATE xplat/web/core/base/app.base-component.ts (258 bytes)                                                            
CREATE xplat/web/core/base/index.ts (38 bytes)                                                                          
CREATE xplat/web/features/index.ts (22 bytes)                                                                           
CREATE xplat/web/features/ui/index.ts (70 bytes)                                                                        
CREATE xplat/web/features/ui/ui.module.spec.ts (150 bytes)                                                              
CREATE xplat/web/features/ui/ui.module.ts (569 bytes)                                                                   
CREATE xplat/web/features/ui/components/index.ts (154 bytes)
CREATE xplat/web/features/ui/components/header/header.component.html (273 bytes)                                        
CREATE xplat/web/features/ui/components/header/header.component.ts (255 bytes)                                          
CREATE xplat/web/scss/package.json (60 bytes)                                                                           
CREATE xplat/web/scss/_index.scss (302 bytes)                                                                           
CREATE xplat/web/scss/_spacing.scss (2382 bytes)                                                                        
CREATE xplat/web/scss/_tags.scss (69 bytes)                                                                             
CREATE xplat/web/scss/_variables.scss (34 bytes)                                                                        
CREATE testing/karma.conf.js (964 bytes)                                                                                
CREATE testing/tsconfig.libs.json (740 bytes)                                                                           
CREATE testing/tsconfig.libs.spec.json (224 bytes)                                                                      
CREATE testing/tsconfig.xplat.json (154 bytes)                                                                          
CREATE testing/tsconfig.xplat.spec.json (276 bytes)                                                                     
CREATE testing/test.libs.ts (618 bytes)                                                                                 
CREATE testing/test.xplat.ts (357 bytes)                                                                                
CREATE tslint.json (232 bytes)                                                                                          
CREATE jest.config.js (275 bytes)                                                                                       
CREATE apps/web-test-app/tsconfig.json (123 bytes)                                                                      
CREATE apps/web-test-app/src/favicon.ico (15086 bytes)
CREATE apps/web-test-app-e2e/tslint.json (48 bytes)                                                                     
CREATE apps/web-test-app-e2e/cypress.json (371 bytes)                                                                   
CREATE apps/web-test-app-e2e/tsconfig.e2e.json (152 bytes)                                                              
CREATE apps/web-test-app-e2e/tsconfig.json (126 bytes)                                                                  
CREATE apps/web-test-app-e2e/src/fixtures/example.json (80 bytes)
CREATE apps/web-test-app-e2e/src/integration/app.spec.ts (232 bytes)                                                    
CREATE apps/web-test-app-e2e/src/plugins/index.js (811 bytes)                                                          
CREATE apps/web-test-app-e2e/src/support/app.po.ts (47 bytes)                                                           
CREATE apps/web-test-app-e2e/src/support/commands.ts (838 bytes)                                                        
CREATE apps/web-test-app-e2e/src/support/index.ts (599 bytes)                                                           
CREATE apps/web-test-app/browserslist (429 bytes)
CREATE apps/web-test-app/tsconfig.app.json (193 bytes)                                                                  
CREATE apps/web-test-app/tslint.json (203 bytes)                                                                        
CREATE apps/web-test-app/src/index.html (355 bytes)                                                                     
CREATE apps/web-test-app/src/main.ts (380 bytes)                                                                        
CREATE apps/web-test-app/src/polyfills.ts (2836 bytes)                                                                  
CREATE apps/web-test-app/src/styles.scss (22 bytes)                                                                     
CREATE apps/web-test-app/src/assets/.gitkeep (0 bytes)                                                                  
CREATE apps/web-test-app/src/environments/environment.prod.ts (51 bytes)                                                
CREATE apps/web-test-app/src/environments/environment.ts (662 bytes)                                                    
CREATE apps/web-test-app/src/app/app.module.ts (411 bytes)                                                              
CREATE apps/web-test-app/src/app/app.component.html (612 bytes)                                                         
CREATE apps/web-test-app/src/app/app.component.spec.ts (2085 bytes)
CREATE apps/web-test-app/src/app/app.component.ts (283 bytes)                                                           
CREATE apps/web-test-app/src/app/app.component.scss (2088 bytes)                                                        
CREATE apps/web-test-app/tsconfig.spec.json (233 bytes)                                                                 
CREATE apps/web-test-app/jest.config.js (273 bytes)                                                                     
CREATE apps/web-test-app/src/test-setup.ts (30 bytes)                                                                   
CREATE apps/web-test-app/src/app/core/core.module.ts (188 bytes)                                                        
CREATE apps/web-test-app/src/app/features/shared/shared.module.ts (220 bytes)                                           
CREATE apps/web-test-app/src/assets/nx-logo.png (71592 bytes)                                                           
CREATE apps/web-test-app/src/assets/xplat.png (12796 bytes)                                                             
CREATE apps/web-test-app/src/assets/i18n/en.json (43 bytes)                                                             
CREATE apps/web-test-app/src/scss/_index.scss (45 bytes)                                                                
CREATE apps/web-test-app/src/scss/_variables.scss (26 bytes)                                                            
CREATE apps/web-test-app/src/app/app.routing.ts (470 bytes)                                                             
CREATE apps/web-test-app/src/app/features/home/home.module.ts (476 bytes)                                               
CREATE apps/web-test-app/src/app/features/home/components/home.component.html (608 bytes)                               
CREATE apps/web-test-app/src/app/features/home/components/home.component.ts (233 bytes)                                 
CREATE apps/web-test-app/src/app/features/home/components/index.ts (134 bytes)                                          
UPDATE .gitignore (766 bytes)                                                                                           
UPDATE tsconfig.json (644 bytes)                                                                                        
UPDATE workspace.json (6487 bytes)                                                                                      
UPDATE nx.json (379 bytes)                                                                                              
UPDATE package.json (2310 bytes)                                                                                        
```

However when I try to start it I get the following error in console:
```
Uncaught Error: The template specified for component HeaderComponent is not a string
    at syntaxError (compiler.js:2175)
    at DirectiveNormalizer.normalizeTemplate (compiler.js:17649)
    at CompileMetadataResolver.loadDirectiveMetadata (compiler.js:19820)
    at compiler.js:25829
    at Array.forEach (<anonymous>)
    at compiler.js:25828
    at Array.forEach (<anonymous>)
    at JitCompiler._loadModules (compiler.js:25825)
    at JitCompiler._compileModuleAndComponents (compiler.js:25805)
    at JitCompiler.compileModuleAsync (compiler.js:25767)
```

Looks like it's a different issue, do you want me to open a new issue for that?

**Comment by NathanWalker** [comment]
Yes if you don’t mind creating separate issue for that would be appreciated and I’ll look into that independently 👍

**Comment by MichalKliment** [comment]
Hi, @NathanWalker is it possible that this issue came again in version 8.0.15?

**Comment by NathanWalker** [comment]
@MichalKliment hey, it's always possible that with patch schematic version updates (from angular devkit or build variants) that things can represent themselves. Could you share the specific stack you see and perhaps your package.json which can always help identify a potential patch issue sometimes.

**Comment by Dutchboy** [comment]
Guys.... The above problem first didn't occur - I didn't even know it existed..... But then I didn't like my own naming conventions of how I'd call my apps, so I deleted it all (the workspace directory completely)

Without knowing, I previously first generated a <nativescript> app and after that a <web> app.

And then the second time (empty workspace again) I first tried to generate a <web> app. And this is where it went south (Mexico?) - the above error appeared.

It all went well when I first generated a <nativescript> and then after that a <web> app!!!! Problem solved.

**Comment by ibaraki-douji** [comment]
I also have this issue, just by doing what is shown in the quick start, and to "fix" it i just installed the "@angular-devkit/schematics" deps into the project (so it's not installed from another dep).
After that, the build went past the package installation (now i'm having other issues xdd, #329 )

The reason is that when generating a new app, the generator will reinstall 4 deps ("@nstudio/angular", "@nstudio/web-angular", ...) which remove the "@angular-devkit/schematics" and reinstall it, tho the "../run-schematic/executor" file IS from the "@angular-devkit/schematics".
