### ISSUE TITLE
(Bug) Ionic: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

### ISSUE THREAD

**Issue by Domvel** [nstudio/xplat#148]
# Bug

> You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

**NOTE** See my repository (on the bottom of this post)

## Expected Behavior

It should work as described in the [docs](https://nstudio.io/xplat/getting-started)

## Current Behavior

It does not work.

## Failure Information (for bugs)

```bash
 nx generate app                                                 
>  NX   NOTE  Nx didn't recognize the command, forwarding on to the Angular CLI.

? What name would you like for this app? app1
? What type of app would like to create? ionic           [Ionic app]
You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
```

### Steps to Reproduce

1. `npm create-xplat-workspace my-apps`. Select empty workspace and Angular CLI.
2. `ng g @nstudio/xplat:init`. Select arch: `Ionic, Angular`, prefix: `ci`
3. `nx generate app`. Select name: `app1`, type: `Ionic`

Result:
Error: `You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.`

### Context

- NX Version 8.4.13
- Xplat Version 8.0.6

**A minimal reproduce scenario using allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs

```bash
 nx generate app                                                 
>  NX   NOTE  Nx didn't recognize the command, forwarding on to the Angular CLI.

? What name would you like for this app? app1
? What type of app would like to create? ionic           [Ionic app]
You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
```

## Other

See [my repository](https://github.com/Domvel/nx-xplat-ionic-demo).

**Comment by NathanWalker** [comment]
The issue seems to come from the executable package create-xplat-workspace.
When you have a moment could you instead try this:
```
npx create-nx-workspace name
cd name
npm i -D @nstudio/xplat
nx g app
```

**Comment by Domvel** [comment]
@NathanWalker I tried it. Same problem. I already wrote this steps above. Ok not with the alias short cut, but it's the same. 

Log:

```text
npx create-nx-workspace my-test-apps
npx: installed 164 in 10.435s
? What to create in the new workspace empty             [an empty workspace]
? CLI to power the Nx workspace       Angular CLI  [Extensible CLI for Angular applications. Recommended for Angular projects.]
Creating a sandbox with Nx...
added 333 packages from 217 contributors and audited 3112 packages in 10.349s
found 0 vulnerabilities

new my-test-apps --preset="empty" --collection=@nrwl/workspace
CREATE my-test-apps/nx.json (203 bytes)
CREATE my-test-apps/tsconfig.json (509 bytes)
CREATE my-test-apps/package.json (1192 bytes)
CREATE my-test-apps/README.md (2698 bytes)
CREATE my-test-apps/.editorconfig (245 bytes)
CREATE my-test-apps/.gitignore (503 bytes)
CREATE my-test-apps/.prettierignore (74 bytes)
CREATE my-test-apps/.prettierrc (26 bytes)
CREATE my-test-apps/angular.json (96 bytes)
CREATE my-test-apps/apps/.gitkeep (1 bytes)
CREATE my-test-apps/libs/.gitkeep (0 bytes)
CREATE my-test-apps/tools/tsconfig.tools.json (218 bytes)
CREATE my-test-apps/tools/schematics/.gitkeep (0 bytes)
CREATE my-test-apps/.vscode/extensions.json (164 bytes)

> @angular/cli@8.3.3 postinstall C:\Users\%username%\Desktop\projects\github\nx\xplat\my-test-apps\node_modules\@angular\cli
> node ./bin/postinstall/script.js

added 410 packages from 264 contributors and audited 3355 packages in 11.89s
found 0 vulnerabilities

    Successfully initialized git.
```

```text
 cd .\my-test-apps\
PS C:\Users\%username%\Desktop\projects\github\nx\xplat\my-test-apps> npm i -D @nstudio/xplat

> @nstudio/xplat@8.0.6 postinstall C:\Users\%username%\Desktop\projects\github\nx\xplat\my-test-apps\node_modules\@nstudio\xplat
> node src/utils/postinstall.js

An issue were detected during patching the nx-formatter Error: Apply couldn't patch for nx format
    at C:\Users\%username%\Desktop\projects\github\nx\xplat\my-test-apps\node_modules\@nstudio\xplat\src\utils\postinstall.js:139:31
    at step (C:\Users\%username%\Desktop\projects\github\nx\xplat\my-test-apps\node_modules\@nstudio\xplat\src\utils\postinstall.js:32:23)
    at Object.next (C:\Users\%username%\Desktop\projects\github\nx\xplat\my-test-apps\node_modules\@nstudio\xplat\src\utils\postinstall.js:13:53)
    at fulfilled (C:\Users\%username%\Desktop\projects\github\nx\xplat\my-test-apps\node_modules\@nstudio\xplat\src\utils\postinstall.js:4:58)

>  XPLAT  Note:

  xplat is updating "C:\Users\%username%\Desktop\projects\github\nx\xplat\my-test-apps\.prettierignore" with a few important extra rules. You may double-check the contents afterwards to ensure they meet your satisfaction.

+ @nstudio/xplat@8.0.6
added 13 packages from 68 contributors and audited 3937 packages in 5.222s
found 0 vulnerabilities
```

```text
nx g app

>  NX   NOTE  Nx didn't recognize the command, forwarding on to the Angular CLI.

? What name would you like for this app? app1
? What type of app would like to create? ionic           [Ionic app]
You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
```

**Comment by NathanWalker** [comment]
Thanks for this @Domvel - I'm taking a look, I noticed Nrwl just release 8.5.0 Nx as well today.
When choosing `empty` with Nx it will usually create a workspace with `workspace.json` and fallback to using Nx cli (instead of angular) which is normal and shouldn't cause an issue. It's the way we prefer to configure Nx ourselves but something recent may have changed which is affecting this.

**Comment by Domvel** [comment]
Nope, there is no workspace.json. Maybe if I use `empty` AND `nx` instead of `empty` and `angular`. 
But empty and angular result is:

```text
my-test-apps
|= .vscode
|  \- extensions.json
|= apps
|  \- .gitkeep
|= libs
|  \- .gitkeep
|= tools
|  |= schematics
|  |  \- .gitkeep
|  \- tsconfig.tools.json
|- .editorconfig
|- .gitignore
|- .prettierignore
|- .prettierrc
|- angular.json
|- nx.json
|- package-lock.json
|- package.json
|- README.md
\- tsconfig.json
```

**Comment by NathanWalker** [comment]
Ah perhaps that's part of issue - maybe. We tend to configure from `empty` with no presets as a starting base with Nx. Since `workspace.json` along with Nx cli solves broader set of cases for us. Perhaps one other try if you create choosing `empty` but instead of choosing angular cli, choose Nx cli and how do things go for you with that?

**Comment by Domvel** [comment]
My selection and possible values of `npm create-nx-workspace name`

![image](https://user-images.githubusercontent.com/35452565/64710404-2d43cd80-d4b8-11e9-995a-5a77fda9cdb2.png)

Enter...

![image](https://user-images.githubusercontent.com/35452565/64710432-3e8cda00-d4b8-11e9-8596-a2420e62dcdc.png)

Enter...

**Comment by NathanWalker** [comment]
Choose `Nx` for the CLI

**Comment by NathanWalker** [comment]
It works with angular projects as well - we've been using exclusively the `nx` cli.

**Comment by paullryan** [comment]
To anyone else that stumbles upon this (and @NathanWalker). Using ng does work but once you start you must continue to use ng (angular-cli) for all generation and init commands as mixing nx commands for generation will not properly tag angular.json and instead will try to populate the workspace.json which is what causes this error with nx 8.5.1+

so this will work on an existing nx project that is using angular-cli
```sh
ng add @nstudio/xplat
ng g @nstudio/xplat:init --prefix=cb --platforms=web,nativescript
ng generate @nstudio/xplat:app app
ng serve nativescript-app 
```

**Comment by erik-slack** [comment]
This was extremely helpful thanks all, especially @paullryan !

**Comment by davidecampello** [comment]
Hi, I don't know why, but I can't use xplat to generate a ionic app.
When I run `npx create-nx-workspace myworkspace` I can't choose nx cli (only stle and if empty), and running, `nx generate app` I'm getting Error: Cannot find module '..../myworkspace/node_modules/@nrwl/cli/bin/nx.js'
Can you help me?
Thanks
