### ISSUE TITLE
Generate feature command fails

### ISSUE THREAD

**Issue by Cselt** [nstudio/xplat#156]
I tired to generate a new project as it is described in the getting started guide. 
After that I added platforms: web, electron and nativescript. Everything was ok so far.

But after that when I try to generate a new feature I get one of the following errors:
```
nx generate @nstudio/angular:feature materials --platforms=web,electron

>  NX   NOTE  Nx didn't recognize the command, forwarding on to the Angular CLI.

RangeError: Maximum call stack size exceeded
    at formatValue (internal/util/inspect.js:511:10)                                                                                                                                         
	at inspect (internal/util/inspect.js:191:10)                                                                                                                                             
	at formatWithOptions (util.js:84:12)                                                                                                                                                     
	at format (util.js:72:10)                                                                                                                                                                
	at Console.console.warn (D:\Workspace\xplat-test\node_modules\@angular\cli\lib\cli\index.js:34:35)                                                                                       
	at Observable._trySubscribe (D:\Workspace\xplat-test\node_modules\@angular\cli\node_modules\rxjs\internal\Observable.js:55:25)                                                           
	at Observable.subscribe (D:\Workspace\xplat-test\node_modules\@angular\cli\node_modules\rxjs\internal\Observable.js:30:22)                                                               
	at SwitchMapOperator.call (D:\Workspace\xplat-test\node_modules\@angular\cli\node_modules\rxjs\internal\operators\switchMap.js:33:23)                                                    
	at Observable.subscribe (D:\Workspace\xplat-test\node_modules\@angular\cli\node_modules\rxjs\internal\Observable.js:25:31)                                                               
	at SwitchMapOperator.call (D:\Workspace\xplat-test\node_modules\@angular\cli\node_modules\rxjs\internal\operators\switchMap.js:33:23)     
```

OR

```
nx generate @nstudio/angular:feature materials --platforms=web,electron

>  NX   NOTE  Nx didn't recognize the command, forwarding on to the Angular CLI.

D:\Workspace\xplat-test\node_modules\@angular\cli\node_modules\rxjs\internal\util\hostReportError.js:4
    setTimeout(function () { throw err; });
                             ^

RangeError: Maximum call stack size exceeded
    at style (D:\Workspace\xplat-test\node_modules\ansi-colors\index.js:46:27)
    at Function.color (D:\Workspace\xplat-test\node_modules\ansi-colors\index.js:62:30)
    at warn (D:\Workspace\xplat-test\node_modules\@angular\cli\lib\cli\index.js:22:65)
    at SafeSubscriber.logger.pipe.subscribe.entry [as _next] (D:\Workspace\xplat-test\node_modules\@angular\cli\node_modules\@angular-devkit\core\node\cli-logger.js:59:34)
    at SafeSubscriber.__tryOrUnsub (D:\Workspace\xplat-test\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:207:16)
    at SafeSubscriber.next (D:\Workspace\xplat-test\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:145:22)
    at Subscriber._next (D:\Workspace\xplat-test\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:89:26)
    at Subscriber.next (D:\Workspace\xplat-test\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:66:18)
    at FilterSubscriber._next (D:\Workspace\xplat-test\node_modules\@angular\cli\node_modules\rxjs\internal\operators\filter.js:52:30)
    at FilterSubscriber.Subscriber.next (D:\Workspace\xplat-test\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:66:18)
```

What is the proper way of creating a new feature? Maybe I missed something.

Thanks!

**Comment by NathanWalker** [comment]
@Cselt thanks for the report. I need to add `feature` support to electron which is the cause to the issue mentioned -- I'll add for electron soon. In meantime you should be able to do the above for `web` at least like this:
```
nx generate @nstudio/angular:feature materials --platforms=web
```

**Comment by Cselt** [comment]
Thanks @NathanWalker, worked fine with `web` only.
