### ISSUE TITLE
New chalk breaks the generation

### ISSUE THREAD

**Issue by norbert-tasi** [nstudio/xplat#184]
Hello,

I've got this error if I use chalk3.0.0

`[error] TypeError: Cannot read property 'bold' of undefined
    at new CLIOutput (C:\development\repo\ntc\node_modules\@nstudio\xplat\src\utils\output.js:12:48)
    at Object.<anonymous> (C:\development\repo\ntc\node_modules\@nstudio\xplat\src\utils\output.js:126:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\development\repo\ntc\node_modules\@nstudio\xplat\src\utils\index.js:10:10)

`

Thanks,

tano

**Comment by NathanWalker** [comment]
This looks to be dependency patch version issue in old version - fixed in 9.0.2
