### ISSUE TITLE
Not able to add admin script

### ISSUE THREAD

**Issue by carrbrpoa** [nstudio/xplat#24]
I started to play with xplat today. Followed instructions from main page, started only with web platform, but in the admin part, when I tried to run `ng g admin` in workspace root, got this error:

```
Schematic "admin" not found in collection "@nstudio/schematics".
Error: Schematic "admin" not found in collection "@nstudio/schematics".
    at SchematicEngine.createSchematic (C:\git\xplat-angular-workspace\node_modules\@angular-devkit\schematics\src\engine\engine.js:224:23)
    at CollectionImpl.createSchematic (C:\git\xplat-angular-workspace\node_modules\@angular-devkit\schematics\src\engine\engine.js:69:29)
    at Object.getSchematic (C:\git\xplat-angular-workspace\node_modules\@angular\cli\utilities\schematics.js:43:23)
    at GenerateCommand.getOptions (C:\git\xplat-angular-workspace\node_modules\@angular\cli\models\schematic-command.js:216:40)
    at GenerateCommand.<anonymous> (C:\git\xplat-angular-workspace\node_modules\@angular\cli\commands\generate.js:45:53)
    at Generator.next (<anonymous>)
    at fulfilled (C:\git\xplat-angular-workspace\node_modules\@angular\cli\commands\generate.js:11:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
```

Windows 8. Node 8.11.4. npm 5.8.0.

**Comment by NathanWalker** [comment]
Good idea! We will add that to the README and in our docs soon 👍
