### ISSUE TITLE
nx 12 / xplat 12.0.2 :init with angular fails on typescript version mismatch

### ISSUE THREAD

**Issue by wstidolph** [nstudio/xplat#266]
Fresh NX workspace, fresh install of xplat 12.0.2, generate 'init' gets error on typescript version mismatch.

````
▓ ~/dev ▓▒░ npx create-nx-workspace@latest                                                                                                                 ░▒▓ ✔ │ base Py │ at 15:12:31 ▓▒░
✔ Workspace name (e.g., org name)     · xptest
✔ What to create in the new workspace · empty
✔ Use Nx Cloud? (It's free and doesn't require registration.) · No

>  NX  Nx is creating your workspace.
...

>  NX   SUCCESS  Nx has successfully created the workspace.

░▒▓ ~/dev ▓▒░ cd xptest                                                                                                                                  ░▒▓ 128 ✘ │ base Py │ at 15:15:08 ▓▒░
░▒▓ ~/dev/xptest │ on master ▓▒░ npm install --save-dev @nstudio/xplat@12.0.2                                                                                ░▒▓ ✔ │ base Py │ at 15:15:12 ▓▒░

added 72 packages, and audited 277 packages in 9s
...

░▒▓ ~/dev/xptest │ on master ▓▒░ nx generate @nstudio/xplat:init                                                                                  ░▒▓ ✔ │ took 16s │ base Py │ at 15:19:38 ▓▒░
✔ Would you like to generate xplat supporting architecture now? You can also generate later with: nx generate @nstudio/xplat:init · web
✔ Do you prefer to use a frontend framework? · angular
✔ Please input a 2-3 character prefix to use with xplat generators: · sse
Note to VS Code users: no development mode set. xplat could not find any VS Code settings in the standard location: /var/local/Code/User/settings.json It's possible you don't have a user settings.json yet. If so, open VS Code User settings and save any kind of setting to have it created.
✔ Packages installed successfully.
✔ Packages installed successfully.
Note to VS Code users: no development mode set. xplat could not find any VS Code settings in the standard location: /var/local/Code/User/settings.json It's possible you don't have a user settings.json yet. If so, open VS Code User settings and save any kind of setting to have it created.
⠧ Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: xptest@0.0.0
npm ERR! Found: typescript@4.2.4
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"~4.2.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@">=4.0 <4.2" from @angular/compiler-cli@11.2.14
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   dev @angular/compiler-cli@"~11.2.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/wstidolph/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wstidolph/.npm/_logs/2021-05-18T22_21_44_241Z-debug.log
✖ Package install failed, see above.
UnsuccessfulWorkflowExecution [Error]: Workflow did not execute successfully.
    at ChildProcess.<anonymous> (/home/wstidolph/dev/xptest/node_modules/@angular-devkit/schematics/tasks/package-manager/executor.js:109:31)
    at ChildProcess.emit (node:events:329:20)
    at maybeClose (node:internal/child_process:1055:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
The generator workflow failed. See above.
````

**Comment by NathanWalker** [comment]
This is related to Angular 12 in latest Nx. We will be releasing angular 12 support once NativeScript supports it in next 1-2 weeks.

In meantime you can generate your workspace like this:

npx create-nx-workspace@12.2.0

**Comment by wstidolph** [comment]
Well, that changed the error, anyway:
````
 ~/dev ▓▒░ npx create-nx-workspace@12.2.0                                                                                                                 ░▒▓ ✔ │ base Py │ at 20:20:33 ▓▒░
Need to install the following packages:
  create-nx-workspace@12.2.0
Ok to proceed? (y) y
✔ Workspace name (e.g., org name)     · xptest
✔ What to create in the new workspace · empty
✔ Use Nx Cloud? (It's free and doesn't require registration.) · No

>  NX  Nx is creating your workspace.
...

>  NX   SUCCESS  Nx has successfully created the workspace.

░▒▓ ~/dev ▓▒░ cd xptest                                                                                                                           ░▒▓ ✔ │ took 42s │ base Py │ at 20:21:41 ▓▒░
░▒▓ ~/dev/xptest │ on master ▓▒░ npm install --save-dev @nstudio/xplat@12.0.2                                                                                ░▒▓ ✔ │ base Py │ at 20:21:49 ▓▒░

added 72 packages, and audited 277 packages in 9s
...
░▒▓ ~/dev/xptest │ on master !3 ▓▒░ nx generate @nstudio/xplat:init                                                                                ░▒▓ ✔ │ took 9s │ base Py │ at 20:22:10 ▓▒░
✔ Would you like to generate xplat supporting architecture now? You can also generate later with: nx generate @nstudio/xplat:init · web
✔ Do you prefer to use a frontend framework? · angular
✔ Please input a 2-3 character prefix to use with xplat generators: · sse
Note to VS Code users: no development mode set. xplat could not find any VS Code settings in the standard location: /var/local/Code/User/settings.json It's possible you don't have a user settings.json yet. If so, open VS Code User settings and save any kind of setting to have it created.
✔ Packages installed successfully.
✔ Packages installed successfully.
Note to VS Code users: no development mode set. xplat could not find any VS Code settings in the standard location: /var/local/Code/User/settings.json It's possible you don't have a user settings.json yet. If so, open VS Code User settings and save any kind of setting to have it created.
⠇ Installing packages (npm)...npm WARN ERESOLVE overriding peer dependency
npm WARN Found: postcss@8.2.14
npm WARN node_modules/@angular-devkit/build-angular/node_modules/postcss
npm WARN   postcss@"8.2.14" from @angular-devkit/build-angular@0.1102.13
npm WARN   node_modules/@angular-devkit/build-angular
npm WARN     dev @angular-devkit/build-angular@"~0.1102.0" from the root project
npm WARN   8 more (autoprefixer, css-loader, cssnano, icss-utils, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer postcss@"^8.2.15" from cssnano-preset-default@5.1.0
npm WARN node_modules/@angular-devkit/build-angular/node_modules/cssnano/node_modules/cssnano-preset-default
npm WARN   cssnano-preset-default@"^5.0.1" from cssnano@5.0.2
npm WARN   node_modules/@angular-devkit/build-angular/node_modules/cssnano
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: postcss@8.2.14
npm WARN node_modules/@angular-devkit/build-angular/node_modules/postcss
npm WARN   postcss@"8.2.14" from @angular-devkit/build-angular@0.1102.13
npm WARN   node_modules/@angular-devkit/build-angular
npm WARN     dev @angular-devkit/build-angular@"~0.1102.0" from the root project
npm WARN   8 more (autoprefixer, css-loader, cssnano, icss-utils, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer postcss@"^8.2.15" from cssnano-preset-default@5.1.0
npm WARN node_modules/@angular-devkit/build-angular/node_modules/cssnano/node_modules/cssnano-preset-default
npm WARN   cssnano-preset-default@"^5.0.1" from cssnano@5.0.2
npm WARN   node_modules/@angular-devkit/build-angular/node_modules/cssnano
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: postcss@8.2.14
npm ERR! node_modules/@angular-devkit/build-angular/node_modules/postcss
npm ERR!   postcss@"8.2.14" from @angular-devkit/build-angular@0.1102.13
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~0.1102.0" from the root project
npm ERR!   peer postcss@"^8.1.0" from autoprefixer@10.2.4
npm ERR!   node_modules/@angular-devkit/build-angular/node_modules/autoprefixer
npm ERR!     autoprefixer@"10.2.4" from @angular-devkit/build-angular@0.1102.13
npm ERR!     node_modules/@angular-devkit/build-angular
npm ERR!       dev @angular-devkit/build-angular@"~0.1102.0" from the root project
npm ERR!   7 more (css-loader, cssnano, icss-utils, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer postcss@"^8.2.15" from cssnano-utils@2.0.1
npm ERR! node_modules/@angular-devkit/build-angular/node_modules/cssnano/node_modules/cssnano-utils
npm ERR!   cssnano-utils@"^2.0.1" from cssnano-preset-default@5.1.0
npm ERR!   node_modules/@angular-devkit/build-angular/node_modules/cssnano/node_modules/cssnano-preset-default
npm ERR!     cssnano-preset-default@"^5.0.1" from cssnano@5.0.2
npm ERR!     node_modules/@angular-devkit/build-angular/node_modules/cssnano
npm ERR!       cssnano@"5.0.2" from @angular-devkit/build-angular@0.1102.13
npm ERR!       node_modules/@angular-devkit/build-angular
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/wstidolph/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wstidolph/.npm/_logs/2021-05-20T03_23_56_501Z-debug.log
✖ Package install failed, see above.
UnsuccessfulWorkflowExecution [Error]: Workflow did not execute successfully.
    at ChildProcess.<anonymous> (/home/wstidolph/dev/xptest/node_modules/@angular-devkit/schematics/tasks/package-manager/executor.js:109:31)
    at ChildProcess.emit (node:events:329:20)
    at maybeClose (node:internal/child_process:1055:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
The generator workflow failed. See above.
````

**Comment by NathanWalker** [comment]
Curious, thanks for the report - will see if can tell anything.
