### ISSUE TITLE
[Bug] Error: Cannot find configuration for app in /angular.json  after generating new workspace

### ISSUE THREAD

**Issue by iameduardod** [nstudio/xplat#273]
Steps:

1. npx create-nx-workspace myworkspace
2. Choose empty
3. No to NX Cloud
4. cd myworkspace
5. npm i @nstudio/xplat -D
6. nx g app
7. name it myapp
8. Choose web
9. Default directory (apps)
10. Yes to routing

Error:

`✔ Would you like to configure routing for this app? (Y/n) · true
✔ Packages installed successfully.
Error: Cannot find configuration for 'web-myapp' in /angular.json.
    at Object.readProjectConfiguration (/Users/<retracted>/Development/codebases/myworkspace/node_modules/@nrwl/devkit/src/generators/project-configuration.js:110:15)
    at updateAppAndE2EProjectConfigurations (/Users/<retracted>/Development/codebases/myworkspace/node_modules/@nrwl/angular/src/generators/application/lib/update-config-files.js:32:30)
    at Object.updateConfigFiles (/Users/<retracted>/Development/codebases/myworkspace/node_modules/@nrwl/angular/src/generators/application/lib/update-config-files.js:10:5)
    at /Users/<retracted>/Development/codebases/myworkspace/node_modules/@nrwl/angular/src/generators/application/application.js:39:15
    at Generator.next (<anonymous>)
    at fulfilled (/Users/<retracted>/Development/codebases/myworkspace/node_modules/tslib/tslib.js:114:62)
Cannot find configuration for 'web-myapp' in /angular.json.`

**Comment by iameduardod** [comment]
Same error if used npm i @nstudio/xplat@12.4.3 -D

Any thoughts @NathanWalker

**Comment by NathanWalker** [comment]
@iameduardod I'm investigating this - Nx 12.5 was just released yesterday and appears related. Will release a patch if can find the culprit soon.

**Comment by NathanWalker** [comment]
https://github.com/nrwl/nx/pull/6170

**Comment by NathanWalker** [comment]
@iameduardod this is fixed with latest Nx (12.5.1) - you can just use `npx create-nx-workspace@latest` and it will work properly now.

**Comment by iameduardod** [comment]
i appreciate your help @NathanWalker  ! <3
