### ISSUE TITLE
I can't to install xplat to my workspace 

### ISSUE THREAD

**Issue by gelleson** [nstudio/xplat#290]
I can't install xplat to my workspace

## Version
angular.json
```json
{
  "version": 1,
  "projects": {
    "action": {
      "root": "apps/action",
      "sourceRoot": "apps/action/src",
      "projectType": "application",
      "architect": {
        "build": {
          "builder": "@nrwl/node:build",
          "outputs": [
            "{options.outputPath}"
          ],
          "options": {
            "outputPath": "dist/apps/action",
            "main": "apps/action/src/main.ts",
            "tsConfig": "apps/action/tsconfig.app.json",
            "assets": [
              "apps/action/src/assets"
            ]
          },
          "configurations": {
            "production": {
              "optimization": true,
              "extractLicenses": true,
              "inspect": false,
              "fileReplacements": [
                {
                  "replace": "apps/action/src/environments/environment.ts",
                  "with": "apps/action/src/environments/environment.prod.ts"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@nrwl/node:execute",
          "options": {
            "buildTarget": "action:build"
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "outputs": [
            "{options.outputFile}"
          ],
          "options": {
            "lintFilePatterns": [
              "apps/action/**/*.ts"
            ]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "outputs": [
            "coverage/apps/action"
          ],
          "options": {
            "jestConfig": "apps/action/jest.config.js",
            "passWithNoTests": true
          }
        }
      },
      "tags": []
    },
    "context-finance": {
      "projectType": "library",
      "root": "libs/context/finance",
      "sourceRoot": "libs/context/finance/src",
      "prefix": "ui",
      "architect": {
        "test": {
          "builder": "@nrwl/jest:jest",
          "outputs": [
            "coverage/libs/context/finance"
          ],
          "options": {
            "jestConfig": "libs/context/finance/jest.config.js",
            "passWithNoTests": true
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": [
              "libs/context/finance/src/**/*.ts",
              "libs/context/finance/src/**/*.html"
            ]
          }
        }
      },
      "tags": []
    },
    "context-keeper": {
      "projectType": "library",
      "root": "libs/context/keeper",
      "sourceRoot": "libs/context/keeper/src",
      "prefix": "fourcore",
      "architect": {
        "test": {
          "builder": "@nrwl/jest:jest",
          "outputs": [
            "coverage/libs/context/keeper"
          ],
          "options": {
            "jestConfig": "libs/context/keeper/jest.config.js",
            "passWithNoTests": true
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": [
              "libs/context/keeper/src/**/*.ts",
              "libs/context/keeper/src/**/*.html"
            ]
          }
        }
      },
      "tags": []
    },
    "context-people": {
      "projectType": "library",
      "root": "libs/context/people",
      "sourceRoot": "libs/context/people/src",
      "prefix": "ui",
      "architect": {
        "test": {
          "builder": "@nrwl/jest:jest",
          "outputs": [
            "coverage/libs/context/people"
          ],
          "options": {
            "jestConfig": "libs/context/people/jest.config.js",
            "passWithNoTests": true
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": [
              "libs/context/people/src/**/*.ts",
              "libs/context/people/src/**/*.html"
            ]
          }
        }
      },
      "tags": []
    },
    "core-finance": {
      "root": "libs/core/finance",
      "sourceRoot": "libs/core/finance/src",
      "projectType": "library",
      "architect": {
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "outputs": [
            "{options.outputFile}"
          ],
          "options": {
            "lintFilePatterns": [
              "libs/core/finance/**/*.ts"
            ]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "outputs": [
            "coverage/libs/core/finance"
          ],
          "options": {
            "jestConfig": "libs/core/finance/jest.config.js",
            "passWithNoTests": true
          }
        }
      },
      "tags": []
    },
    "core-hasura": {
      "root": "libs/core/hasura",
      "sourceRoot": "libs/core/hasura/src",
      "projectType": "library",
      "architect": {
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "outputs": [
            "{options.outputFile}"
          ],
          "options": {
            "lintFilePatterns": [
              "libs/core/hasura/**/*.ts"
            ]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "outputs": [
            "coverage/libs/core/hasura"
          ],
          "options": {
            "jestConfig": "libs/core/hasura/jest.config.js",
            "passWithNoTests": true
          }
        }
      },
      "tags": []
    },
    "core-integration": {
      "root": "libs/core/integration",
      "sourceRoot": "libs/core/integration/src",
      "projectType": "library",
      "architect": {
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "outputs": [
            "{options.outputFile}"
          ],
          "options": {
            "lintFilePatterns": [
              "libs/core/integration/**/*.ts"
            ]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "outputs": [
            "coverage/libs/core/integration"
          ],
          "options": {
            "jestConfig": "libs/core/integration/jest.config.js",
            "passWithNoTests": true
          }
        }
      },
      "tags": []
    },
    "core-keeper": {
      "root": "libs/core/keeper",
      "sourceRoot": "libs/core/keeper/src",
      "projectType": "library",
      "architect": {
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "outputs": [
            "{options.outputFile}"
          ],
          "options": {
            "lintFilePatterns": [
              "libs/core/keeper/**/*.ts"
            ]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "outputs": [
            "coverage/libs/core/keeper"
          ],
          "options": {
            "jestConfig": "libs/core/keeper/jest.config.js",
            "passWithNoTests": true
          }
        }
      },
      "tags": []
    },
    "core-storage": {
      "root": "libs/core/storage",
      "sourceRoot": "libs/core/storage/src",
      "projectType": "library",
      "architect": {
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "outputs": [
            "{options.outputFile}"
          ],
          "options": {
            "lintFilePatterns": [
              "libs/core/storage/**/*.ts"
            ]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "outputs": [
            "coverage/libs/core/storage"
          ],
          "options": {
            "jestConfig": "libs/core/storage/jest.config.js",
            "passWithNoTests": true
          }
        }
      },
      "tags": []
    },
    "finance": {
      "projectType": "application",
      "root": "apps/finance",
      "sourceRoot": "apps/finance/src",
      "prefix": "fourcore",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "outputs": [
            "{options.outputPath}"
          ],
          "options": {
            "outputPath": "dist/apps/finance",
            "index": "apps/finance/src/index.html",
            "main": "apps/finance/src/main.ts",
            "polyfills": "apps/finance/src/polyfills.ts",
            "tsConfig": "apps/finance/tsconfig.app.json",
            "inlineStyleLanguage": "scss",
            "assets": [
              "apps/finance/src/favicon.ico",
              "apps/finance/src/assets",
              "apps/finance/src/manifest.webmanifest",
              {
                "glob": "**/*",
                "input": "./node_modules/@ant-design/icons-angular/src/inline-svg/",
                "output": "/assets/"
              }
            ],
            "styles": [
              "apps/finance/src/theme.less",
              "apps/finance/src/styles.scss"
            ],
            "scripts": [],
            "serviceWorker": true,
            "ngswConfigPath": "apps/finance/ngsw-config.json"
          },
          "configurations": {
            "production": {
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "500kb",
                  "maximumError": "10mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kb",
                  "maximumError": "4kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "apps/finance/src/environments/environment.ts",
                  "with": "apps/finance/src/environments/environment.prod.ts"
                }
              ],
              "outputHashing": "all"
            },
            "dev": {
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "500kb",
                  "maximumError": "10mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kb",
                  "maximumError": "4kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "apps/finance/src/environments/environment.ts",
                  "with": "apps/finance/src/environments/environment.dev.ts"
                }
              ],
              "outputHashing": "all"
            },
            "development": {
              "buildOptimizer": false,
              "optimization": false,
              "vendorChunk": true,
              "extractLicenses": false,
              "sourceMap": true,
              "namedChunks": true
            }
          },
          "defaultConfiguration": "production"
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "configurations": {
            "production": {
              "browserTarget": "finance:build:production"
            },
            "dev": {
              "browserTarget": "finance:build:dev"
            },
            "development": {
              "browserTarget": "finance:build:development"
            }
          },
          "defaultConfiguration": "development"
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "finance:build"
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": [
              "apps/finance/src/**/*.ts",
              "apps/finance/src/**/*.html"
            ]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "outputs": [
            "coverage/apps/finance"
          ],
          "options": {
            "jestConfig": "apps/finance/jest.config.js",
            "passWithNoTests": true
          }
        }
      },
      "tags": []
    },
    "finance-e2e": {
      "root": "apps/finance-e2e",
      "sourceRoot": "apps/finance-e2e/src",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@nrwl/cypress:cypress",
          "options": {
            "cypressConfig": "apps/finance-e2e/cypress.json",
            "devServerTarget": "finance:serve:development"
          },
          "configurations": {
            "production": {
              "devServerTarget": "finance:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "outputs": [
            "{options.outputFile}"
          ],
          "options": {
            "lintFilePatterns": [
              "apps/finance-e2e/**/*.{js,ts}"
            ]
          }
        }
      },
      "tags": [],
      "implicitDependencies": [
        "finance"
      ]
    },
    "fourcore-shared": {
      "projectType": "library",
      "root": "libs/ui/shared",
      "sourceRoot": "libs/ui/shared/src",
      "prefix": "fourcore",
      "architect": {
        "test": {
          "builder": "@nrwl/jest:jest",
          "outputs": [
            "coverage/libs/ui/shared"
          ],
          "options": {
            "jestConfig": "libs/ui/shared/jest.config.js",
            "passWithNoTests": true
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": [
              "libs/ui/shared/src/**/*.ts",
              "libs/ui/shared/src/**/*.html"
            ]
          }
        }
      },
      "tags": []
    },
    "keeper": {
      "projectType": "application",
      "root": "apps/keeper",
      "sourceRoot": "apps/keeper/src",
      "prefix": "fourcore",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "outputs": [
            "{options.outputPath}"
          ],
          "options": {
            "outputPath": "dist/apps/keeper",
            "index": "apps/keeper/src/index.html",
            "main": "apps/keeper/src/main.ts",
            "polyfills": "apps/keeper/src/polyfills.ts",
            "tsConfig": "apps/keeper/tsconfig.app.json",
            "inlineStyleLanguage": "scss",
            "assets": [
              "apps/keeper/src/favicon.ico",
              "apps/keeper/src/assets",
              {
                "glob": "**/*",
                "input": "./node_modules/@ant-design/icons-angular/src/inline-svg/",
                "output": "/assets/"
              }
            ],
            "styles": [
              "apps/keeper/src/styles.scss",
              "apps/keeper/src/theme.less",
              "node_modules/prismjs/themes/prism-okaidia.css",
              "node_modules/prismjs/plugins/line-numbers/prism-line-numbers.css"
            ],
            "scripts": [
              "node_modules/marked/lib/marked.js",
              "node_modules/marked/lib/marked.js",
              "node_modules/prismjs/prism.js",
              "node_modules/prismjs/components/prism-csharp.min.js",
              "node_modules/prismjs/components/prism-css.min.js",
              "node_modules/prismjs/plugins/line-numbers/prism-line-numbers.js",
            ]
          },
          "configurations": {
            "production": {
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "500kb",
                  "maximumError": "1mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kb",
                  "maximumError": "4kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "apps/keeper/src/environments/environment.ts",
                  "with": "apps/keeper/src/environments/environment.prod.ts"
                }
              ],
              "outputHashing": "all"
            },
            "development": {
              "buildOptimizer": false,
              "optimization": false,
              "vendorChunk": true,
              "extractLicenses": false,
              "sourceMap": true,
              "namedChunks": true
            }
          },
          "defaultConfiguration": "production"
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "configurations": {
            "production": {
              "browserTarget": "keeper:build:production"
            },
            "development": {
              "browserTarget": "keeper:build:development"
            }
          },
          "defaultConfiguration": "development"
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "keeper:build"
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": [
              "apps/keeper/src/**/*.ts",
              "apps/keeper/src/**/*.html"
            ]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "outputs": [
            "coverage/apps/keeper"
          ],
          "options": {
            "jestConfig": "apps/keeper/jest.config.js",
            "passWithNoTests": true
          }
        }
      },
      "tags": []
    },
    "keeper-e2e": {
      "root": "apps/keeper-e2e",
      "sourceRoot": "apps/keeper-e2e/src",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@nrwl/cypress:cypress",
          "options": {
            "cypressConfig": "apps/keeper-e2e/cypress.json",
            "devServerTarget": "keeper:serve:development"
          },
          "configurations": {
            "production": {
              "devServerTarget": "keeper:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "outputs": [
            "{options.outputFile}"
          ],
          "options": {
            "lintFilePatterns": [
              "apps/keeper-e2e/**/*.{js,ts}"
            ]
          }
        }
      },
      "tags": [],
      "implicitDependencies": [
        "keeper"
      ]
    },
    "people": {
      "projectType": "application",
      "root": "apps/people",
      "sourceRoot": "apps/people/src",
      "prefix": "fourcore",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "outputs": [
            "{options.outputPath}"
          ],
          "options": {
            "outputPath": "dist/apps/people",
            "index": "apps/people/src/index.html",
            "main": "apps/people/src/main.ts",
            "polyfills": "apps/people/src/polyfills.ts",
            "tsConfig": "apps/people/tsconfig.app.json",
            "inlineStyleLanguage": "scss",
            "assets": [
              "apps/people/src/favicon.ico",
              "apps/people/src/assets",
              {
                "glob": "**/*",
                "input": "./node_modules/@ant-design/icons-angular/src/inline-svg/",
                "output": "/assets/"
              }
            ],
            "styles": [
              "apps/people/src/styles.scss",
              "apps/people/src/theme.less"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "500kb",
                  "maximumError": "10mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kb",
                  "maximumError": "4kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "apps/people/src/environments/environment.ts",
                  "with": "apps/people/src/environments/environment.prod.ts"
                }
              ],
              "outputHashing": "all"
            },
            "dev": {
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "500kb",
                  "maximumError": "10mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kb",
                  "maximumError": "4kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "apps/people/src/environments/environment.ts",
                  "with": "apps/people/src/environments/environment.dev.ts"
                }
              ],
              "outputHashing": "all"
            },
            "development": {
              "buildOptimizer": false,
              "optimization": false,
              "vendorChunk": true,
              "extractLicenses": false,
              "sourceMap": true,
              "namedChunks": true
            }
          },
          "defaultConfiguration": "production"
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "configurations": {
            "production": {
              "browserTarget": "people:build:production"
            },
            "development": {
              "browserTarget": "people:build:development"
            }
          },
          "defaultConfiguration": "development"
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "people:build"
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": [
              "apps/people/src/**/*.ts",
              "apps/people/src/**/*.html"
            ]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "outputs": [
            "coverage/apps/people"
          ],
          "options": {
            "jestConfig": "apps/people/jest.config.js",
            "passWithNoTests": true
          }
        }
      },
      "tags": []
    },
    "people-e2e": {
      "root": "apps/people-e2e",
      "sourceRoot": "apps/people-e2e/src",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@nrwl/cypress:cypress",
          "options": {
            "cypressConfig": "apps/people-e2e/cypress.json",
            "devServerTarget": "people:serve:development"
          },
          "configurations": {
            "production": {
              "devServerTarget": "people:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "outputs": [
            "{options.outputFile}"
          ],
          "options": {
            "lintFilePatterns": [
              "apps/people-e2e/**/*.{js,ts}"
            ]
          }
        }
      },
      "tags": [],
      "implicitDependencies": [
        "people"
      ]
    },
    "ui-core-data-access": {
      "projectType": "library",
      "root": "libs/ui/core/data-access",
      "sourceRoot": "libs/ui/core/data-access/src",
      "prefix": "fourcore",
      "architect": {
        "test": {
          "builder": "@nrwl/jest:jest",
          "outputs": [
            "coverage/libs/ui/core/data-access"
          ],
          "options": {
            "jestConfig": "libs/ui/core/data-access/jest.config.js",
            "passWithNoTests": true
          }
        },
        "generate": {
          "builder": "@nrwl/workspace:run-commands",
          "options": {
            "commands": [
              {
                "command": "graphql-codegen --config libs/ui/core/data-access/codegen.yml"
              }
            ]
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": [
              "libs/ui/core/data-access/src/**/*.ts",
              "libs/ui/core/data-access/src/**/*.html"
            ]
          }
        }
      },
      "tags": []
    }
  }
}

```
package.json
```json
{
  "name": "ui",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "nx",
    "postinstall": "node ./decorate-angular-cli.js && ngcc --properties es2015 browser module main",
    "start": "nx serve --proxy-config proxy.json",
    "build": "nx build",
    "affected:build": "nx affected:build",
    "test": "nx test",
    "introspect:local": "scripty",
    "introspect:dev": "scripty"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "13.1.1",
    "@angular/common": "13.1.1",
    "@angular/compiler": "13.1.1",
    "@angular/core": "13.1.1",
    "@angular/forms": "13.1.1",
    "@angular/platform-browser": "13.1.1",
    "@angular/platform-browser-dynamic": "13.1.1",
    "@angular/pwa": "^13.0.1",
    "@angular/router": "13.1.1",
    "@angular/service-worker": "13.1.1",
    "@apollo/client": "3.5.6",
    "@gerhobbelt/markdown-it-prism": "^2.1.8-5",
    "@golevelup/nestjs-graphql-request": "^0.1.7",
    "@golevelup/nestjs-hasura": "^1.3.1",
    "@graphql-codegen/typescript-graphql-request": "^4.3.3",
    "@nestjs/common": "^7.0.0",
    "@nestjs/core": "^7.0.0",
    "@nestjs/graphql": "^9.1.2",
    "@nestjs/platform-express": "^7.0.0",
    "@nrwl/angular": "13.4.1",
    "@nstudio/xplat": "^13.4.1",
    "apollo-angular": "^2.6.0",
    "apollo-link-ws": "^1.0.20",
    "apollo-server-express": "^3.5.0",
    "aws-sdk": "^2.1048.0",
    "component": "^1.1.0",
    "graphql-request": "^3.7.0",
    "graphql-upload": "^13.0.0",
    "markdown-diff": "^1.0.3",
    "markdown-it": "^12.3.0",
    "markdown-it-markmap": "^0.1.0",
    "markdown-it-plantuml": "^1.4.1",
    "markdown-it-prism": "^2.2.1",
    "markdown-it-textual-uml": "^0.1.9",
    "nestjs-s3": "^1.0.1",
    "ng-zorro-antd": "^12.0.2",
    "ngx-cookie": "^5.0.2",
    "ngx-markdown": "^13.0.0",
    "ngx-markdown-it": "^0.1.2",
    "prismjs": "^1.25.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "~6.6.0",
    "search-query-parser": "^1.6.0",
    "subscriptions-transport-ws": "^0.11.0",
    "tailwindcss": "^2.2.19",
    "tslib": "^2.0.0",
    "zone.js": "0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "13.1.2",
    "@angular-eslint/eslint-plugin": "13.0.1",
    "@angular-eslint/eslint-plugin-template": "13.0.1",
    "@angular-eslint/template-parser": "13.0.1",
    "@angular/cli": "13.1.2",
    "@angular/compiler-cli": "13.1.1",
    "@angular/language-service": "13.1.1",
    "@graphql-codegen/cli": "^2.3.1",
    "@graphql-codegen/typescript-apollo-angular": "^3.3.0",
    "@graphql-codegen/typescript-operations": "^2.2.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^7.0.0",
    "@ngneat/tailwind": "^7.0.3",
    "@nrwl/cli": "13.4.1",
    "@nrwl/cypress": "13.4.1",
    "@nrwl/eslint-plugin-nx": "13.4.1",
    "@nrwl/jest": "13.4.1",
    "@nrwl/linter": "13.4.1",
    "@nrwl/nest": "13.4.1",
    "@nrwl/node": "13.4.1",
    "@nrwl/tao": "13.4.1",
    "@nrwl/workspace": "13.4.1",
    "@types/jest": "27.0.2",
    "@types/markdown-it": "^12.2.3",
    "@types/markdown-it-plantuml": "^1.4.1",
    "@types/node": "14.14.33",
    "@typescript-eslint/eslint-plugin": "5.3.1",
    "@typescript-eslint/parser": "5.3.1",
    "autoprefixer": "^10.4.0",
    "cypress": "^8.3.0",
    "eslint": "8.2.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "graphql": "^15.8.0",
    "graphqurl": "^1.0.1",
    "jest": "27.2.3",
    "jest-preset-angular": "11.0.0",
    "postcss": "^8.3.11",
    "prettier": "^2.3.1",
    "scripty": "^2.0.0",
    "ts-jest": "27.0.5",
    "typescript": "4.4.2"
  }
}

```

nx.json
```json
{
  "npmScope": "fourcore",
  "affected": {
    "defaultBase": "main"
  },
  "cli": {
    "defaultCollection": "@nstudio/xplat",
    "packageManager": "npm"
  },
  "implicitDependencies": {
    "package.json": {
      "dependencies": "*",
      "devDependencies": "*"
    },
    ".eslintrc.json": "*"
  },
  "tasksRunnerOptions": {
    "default": {
      "runner": "@nrwl/workspace/tasks-runners/default",
      "options": {
        "cacheableOperations": [
          "build",
          "lint",
          "test",
          "e2e"
        ],
        "parallel": 1
      }
    }
  },
  "targetDependencies": {
    "build": [
      {
        "target": "build",
        "projects": "dependencies"
      }
    ]
  },
  "generators": {
    "@nrwl/angular:application": {
      "style": "css",
      "linter": "eslint",
      "unitTestRunner": "jest",
      "e2eTestRunner": "cypress"
    },
    "@nrwl/angular:library": {
      "linter": "eslint",
      "unitTestRunner": "jest"
    },
    "@nrwl/angular:component": {
      "style": "scss"
    }
  },
  "defaultProject": "finance"
}
```

## Command

```bash
ng add @nstudio/xplat -v 
```

## Output 

```bash
+ @nstudio/xplat@13.4.1
updated 1 package and audited 2649 packages in 7.327s

175 packages are looking for funding
  run `npm fund` for details

found 74 vulnerabilities (3 low, 24 moderate, 40 high, 7 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
ValueExpected in /Users/gelleson/Documents/Projects/Personal/fourcore/ui/angular.json at position 15167
(node:7516) UnhandledPromiseRejectionWarning: Error: Command failed: npm install @nstudio/xplat && npx nx g @nstudio/xplat:ng-add
    at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at /Users/gelleson/Documents/Projects/Personal/fourcore/ui/node_modules/@nrwl/cli/lib/init-local.js:72:54
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7516) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7516) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by gelleson** [comment]
If it can help, I can provide access to repo

**Comment by gelleson** [comment]
Sorry it was my mistake. I had not valid json in angular.json
