### ISSUE TITLE
NestJS app fails to install

### ISSUE THREAD

**Issue by dmitryr117** [nstudio/xplat#303]
When starting a nest app i keep getting this:

```
root@0a61fb8bdeb3:/devarea/nx-handyman# npx nx g app
✔ What name would you like for this app? · api
✔ What type of app would like to create? · nest
✔ In which directory should the app be generated? (Just press Enter for the default: directly in 'apps') · 
✔ Would you like to configure routing for this app? (Y/n) · true

> XPLAT  Note:

  Generating "nest" app in your workspace. Just so you know, "nest" does not have an xplat supporting architecture layer yet. If you'd like to see "nest" with an xplat layer in future, please add an issue to https://github.com/nstudio/xplat/issues with some details of how you'd like it to work and we'll look into adding to a future release.

✔ Packages installed successfully.
InvalidInputOptions [Error]: Schematic input does not validate against the Schema: {"name":"nest-api","platforms":"nest","directory":"","routing":true,"groupByName":false,"setupSandbox":false,"skipInstall":false,"prefix":"nx-handyman"}
Errors:

  Data path "" must NOT have additional properties(platforms).
    at MapSubscriber.project (/devarea/nx-handyman/node_modules/@angular-devkit/schematics/tools/schema-option-transform.js:30:27)
    at MapSubscriber._next (/devarea/nx-handyman/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/devarea/nx-handyman/node_modules/rxjs/internal/Subscriber.js:66:18)
    at ThrowIfEmptySubscriber._next (/devarea/nx-handyman/node_modules/rxjs/internal/operators/throwIfEmpty.js:44:26)
    at ThrowIfEmptySubscriber.Subscriber.next (/devarea/nx-handyman/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TakeSubscriber._next (/devarea/nx-handyman/node_modules/rxjs/internal/operators/take.js:54:30)
    at TakeSubscriber.Subscriber.next (/devarea/nx-handyman/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/devarea/nx-handyman/node_modules/rxjs/internal/operators/mergeMap.js:93:26)
    at SimpleInnerSubscriber._next (/devarea/nx-handyman/node_modules/rxjs/internal/innerSubscribe.js:27:21)
    at SimpleInnerSubscriber.Subscriber.next (/devarea/nx-handyman/node_modules/rxjs/internal/Subscriber.js:66:18) {
  errors: [
    {
      instancePath: '',
      schemaPath: '#/additionalProperties',
      keyword: 'additionalProperties',
      params: [Object],
      message: 'must NOT have additional properties'
    }
  ]
}
Schematic input does not validate against the Schema: {"name":"nest-api","platforms":"nest","directory":"","routing":true,"groupByName":false,"setupSandbox":false,"skipInstall":false,"prefix":"nx-handyman"}
Errors:

  Data path "" must NOT have additional properties(platforms).
```

Here is what my package.json looks like. I tried with `npx create-nx-workspace@13.4.3` aw well, but same thing.:
```
{
  "name": "my-test-app",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "start": "nx serve",
    "build": "nx build",
    "test": "nx test"
  },
  "private": true,
  "devDependencies": {
    "@nrwl/cli": "13.9.5",
    "@nrwl/workspace": "13.9.5",
    "@nstudio/xplat": "^13.4.3",
    "@types/node": "16.11.7",
    "nx": "13.9.5",
    "prettier": "^2.5.1",
    "typescript": "~4.5.2",
    "@nrwl/nest": "^13.0.0"
  },
  "dependencies": {},
  "xplat": {
    "prefix": ""
  }
}
```

**Comment by rckgomz** [comment]
+1
