### ISSUE TITLE
xplat 14.3:  Non-string value passed to `ts.resolveTypeReferenceDirective

### ISSUE THREAD

**Issue by ReneMueller4P** [nstudio/xplat#312]
Hi there when i compile my project i get now this error 

`\node_modules\typescript\lib\typescript.js:42530
        ts.Debug.assert(typeof typeReferenceDirectiveName === "string", "Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
");
                 ^

Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
    at Object.resolveTypeReferenceDirective (C:\Entwicklung\frontend\node_modules\typescript\lib\typescript.js:42530:18)
    at C:\Entwicklung\frontend\node_modules\@ngtools\webpack\src\ivy\host.js:169:35
    at Array.map (<anonymous>)
    at Object.host.resolveTypeReferenceDirectives (C:\Entwicklung\frontend\node_modules\@ngtools\webpack\src\ivy\host.js:168:32)
    at actualResolveTypeReferenceDirectiveNamesWorker (C:\Entwicklung\frontend\node_modules\typescript\lib\typescript.js:116611:163)
    at resolveTypeReferenceDirectiveNamesWorker (C:\Entwicklung\frontend\node_modules\typescript\lib\typescript.js:116911:26)
    at processTypeReferenceDirectives (C:\Entwicklung\frontend\node_modules\typescript\lib\typescript.js:118393:31)
    at findSourceFileWorker (C:\Entwicklung\frontend\node_modules\typescript\lib\typescript.js:118278:21)
    at findSourceFile (C:\Entwicklung\frontend\node_modules\typescript\lib\typescript.js:118133:26)
    at processImportedModules (C:\Entwicklung\frontend\node_modules\typescript\lib\typescript.js:118539:25)
    at findSourceFileWorker (C:\Entwicklung\frontend\node_modules\typescript\lib\typescript.js:118284:17)
    at findSourceFile (C:\Entwicklung\frontend\node_modules\typescript\lib\typescript.js:118133:26)
    at processImportedModules (C:\Entwicklung\frontend\node_modules\typescript\lib\typescript.js:118539:25)
    at findSourceFileWorker (C:\Entwicklung\frontend\node_modules\typescript\lib\typescript.js:118284:17)
    at findSourceFile (C:\Entwicklung\frontend\node_modules\typescript\lib\typescript.js:118133:26)
    at processImportedModules (C:\Entwicklung\frontend\node_modules\typescript\lib\typescript.js:118539:25)
`
my package.json file 

{
  "name": "frontend",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "nx": "nx",
    "start": "nx serve",
    "build": "nx build",
    "prebuild:web": "checkForUncommittedChanges.bat",
    "build:web": "gulp default --sys core && nx build web-dashboard",
    "build:deploy:web": "npm run build:web && copyProductionToServer.bat",
    "serve:web": "gulp default --sys && nx run web-dashboard:serve",
    "serve:android": "gulp app && nx run nativescript-dashboard:android",
    "build:android": "npx rimraf apps/nativescript-dashboard/platforms/android/app/build/outputs/apk/debug/app-debug.apk && set PRODUCTION=1 &&gulp app &&nx run nativescript-dashboard:android ",
    "test": "nx test",
    "lint": "nx workspace-lint && nx lint",
    "e2e": "nx e2e",
    "affected:apps": "nx affected:apps",
    "affected:libs": "nx affected:libs",
    "affected:build": "nx affected:build",
    "affected:e2e": "nx affected:e2e",
    "affected:test": "nx affected:test",
    "affected:lint": "nx affected:lint",
    "affected:dep-graph": "nx affected:dep-graph",
    "affected": "nx affected",
    "format": "nx format:write",
    "format:write": "nx format:write",
    "format:check": "nx format:check",
    "update": "nx migrate latest",
    "workspace-generator": "nx workspace-generator",
    "dep-graph": "nx dep-graph",
    "help": "nx help",
    "postinstall": "ngcc --properties es2020 browser module main",
    "clean": "npx rimraf hooks node_modules package-lock.json && yarn config set ignore-engines true && yarn",
   
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~14.0.0",
    "@angular/cdk": "~14.0.0",
    "@angular/cdk-experimental": "~14.0.0",
    "@angular/common": "~14.0.0",
    "@angular/compiler": "~14.0.0",
    "@angular/core": "~14.0.0",
    "@angular/forms": "~14.0.0",
    "@angular/platform-browser": "~14.0.0",
    "@angular/platform-browser-dynamic": "~14.0.0",
    "@angular/router": "~14.0.0",
    "@auth0/angular-jwt": "^5.0.2",
    "@bradmartin/nativescript-urlhandler": "^2.0.1",
    "@frontend/xplat-scss": "file:libs/xplat/scss/src",
    "@nativescript/angular": "^13.0.4",
    "@nativescript/core": "8.2.4-alpha.1",
    "@nativescript/facebook": "^2.0.0",
    "@nativescript/firebase-auth": "^1.2.2",
    "@ngneat/until-destroy": "^8.1.4",
    "@ngx-translate/core": "~13.0.0",
    "@ngx-translate/http-loader": "~6.0.0",
    "@sergeymell/nativescript-svg": "^1.1.2",
    "@types/chartist": "^0.11.0",
    "@types/googlemaps": "^3.43.3",
    "@web/styles": "file:libs/xplat/web/scss/src",
    "chartist": "^0.11.4",
    "core-js": "^3.6.5",
    "dayjs": "^1.10.7",
    "dotenv-webpack": "^7.1.0",
    "env-cmd": "^10.1.0",
    "git-repo-info": "^2.1.1",
    "gulp": "^4.0.2",
    "gulp-streamify": "^1.0.2",
    "libphonenumber-js": "^1.10.6",
    "nativescript-barcodescanner": "^4.1.2",
    "nativescript-couchbase-plugin": "^0.9.6",
    "nativescript-dna-deviceinfo": "^3.7.3",
    "nativescript-ngx-fonticon": "~7.0.0",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-ui-listview": "^10.0.2",
    "ng-process-env": "^1.0.6",
    "ngx-auto-unsubscribe-decorator": "^1.1.0",
    "npm": "7.5",
    "qrcode-svg": "^1.1.0",
    "rxjs": "^6.6.0",
    "s": "^1.0.0",
    "stacktrace-js": "^2.0.2",
    "tslib": "^2.0.0",
    "util": "^0.12.4",
    "zone.js": "~0.11.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.1400.2",
    "@angular-devkit/build-angular": "~14.0.0",
    "@angular-devkit/core": "~14.0.0",
    "@angular-devkit/schematics": "~14.0.0",
    "@angular-eslint/eslint-plugin": "~13.5.0",
    "@angular-eslint/eslint-plugin-template": "~13.5.0",
    "@angular-eslint/template-parser": "13.2.1",
    "@angular/compiler-cli": "~14.0.0",
    "@angular/language-service": "~14.0.0",
    "@babel/preset-env": "^7.14.8",
    "@babel/preset-typescript": "^7.16.5",
    "@ckeditor/ckeditor5-angular": "^2.0.2",
    "@faker-js/faker": "^7.2.0",
    "@nativescript/eslint-plugin": "~0.0.4",
    "@nativescript/types": "~8.2.0",
    "@nativescript/webpack": "~5.0.6",
    "@ngtools/webpack": "^13.1.3",
    "@nrwl/angular": "14.3.6",
    "@nrwl/cli": "14.3.6",
    "@nrwl/cypress": "14.3.6",
    "@nrwl/eslint-plugin-nx": "14.3.6",
    "@nrwl/jest": "14.3.6",
    "@nrwl/linter": "14.3.6",
    "@nrwl/nx-cloud": "14.1.2",
    "@nrwl/workspace": "14.3.6",
    "@nstudio/angular": "14.3.0",
    "@nstudio/nativescript": "14.3.0",
    "@nstudio/nativescript-angular": "14.3.0",
    "@nstudio/web": "14.3.0",
    "@nstudio/web-angular": "14.3.0",
    "@nstudio/xplat": "14.3.0",
    "@types/jest": "~28.1.1",
    "@types/node": "^17.0.00",
    "@typescript-eslint/eslint-plugin": "5.24.0",
    "@typescript-eslint/parser": "5.24.0",
    "codelyzer": "~6.0.0",
    "cypress": "^6.0.1",
    "dotenv": "^10.0.0",
    "eslint": "8.15.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "gulp-svg-sprite": "^1.5.0",
    "gulp-svg2png": "^2.0.2",
    "jest": "^28.1.1",
    "jest-environment-jsdom": "^28.1.1",
    "jest-jasmine2": "^28.1.1",
    "jest-preset-angular": "11.1.2",
    "ng-mocks": "^13.5.2",
    "nx": "14.3.6",
    "prettier": "2.6.2",
    "sass": "^1.30.0",
    "ts-jest": "^28.0.4",
    "ts-loader": "~9.2.6",
    "ts-mockito": "^2.6.1",
    "ts-node": "~10.8.1",
    "ts-node-dev": "^2.0.0",
    "typescript": "~4.7.2"
  },
  "xplat": {
    "prefix": "frontend",
    "framework": "angular"
  }
}

Have you any idea how i can fix this issue ? I work on windows.

Thanks for help

**Comment by ReneMueller4P** [comment]
When i downgrade typescript to 4.6.4 all works fine. I hope that helps you @NathanWalker.
