### ISSUE TITLE
missing postinstall.js

### ISSUE THREAD

**Issue by vance** [nstudio/xplat#41]
Seems like I can still build and run tests, but after the initial yarn I get

```
$ node scripts/postinstall.js
module.js:549
    throw err;
    ^

Error: Cannot find module '/Users/xxx/code/xplat/scripts/postinstall.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by vance** [comment]
oh, maybe just needed the --ignore-scripts flag...
