### ISSUE TITLE
Couldn't run NativeScript app with AOT enabled

### ISSUE THREAD

**Issue by benedictkhoo** [nstudio/xplat#59]
Hi, I created a NativeScript app and tried running it with AOT enabled, but I got the following error:

```
System.err: com.tns.NativeScriptException: 
System.err: Calling js method onCreate failed
System.err: 
System.err: TypeError: Cannot read property 'name' of undefined
System.err: File: "file:///data/data/org.nativescript.client/files/app/vendor.js, line: 24892, column: 128
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.client/files/app/vendor.js', line: 24892, column: 129
System.err: 	Frame: function:'push.../../../node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js.ZoneDelegate.invoke', file:'file:///data/data/org.nativescript.client/files/app/vendor.js', line: 56413, column: 26
System.err: 	Frame: function:'onInvoke', file:'file:///data/data/org.nativescript.client/files/app/vendor.js', line: 24427, column: 33
System.err: 	Frame: function:'push.../../../node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js.ZoneDelegate.invoke', file:'file:///data/data/org.nativescript.client/files/app/vendor.js', line: 56412, column: 32
System.err: 	Frame: function:'push.../../../node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js.Zone.run', file:'file:///data/data/org.nativescript.client/files/app/vendor.js', line: 56163, column: 43
System.err: 	Frame: function:'push.../../../node_modules/@angular/core/fesm5/core.js.NgZone.run', file:'file:///data/data/org.nativescript.client/files/app/vendor.js', line: 24341, column: 28
System.err: 	Frame: function:'push.../../../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModuleFactory', file:'file:///data/data/org.nativescript.client/files/app/vendor.js', line: 24891, column: 23
System.err: 	Frame: function:'_bootstrapper', file:'file:///data/data/org.nativescript.client/files/app/vendor.js', line: 52840, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.client/files/app/vendor.js', line: 52916, column: 19
System.err: 	Frame: function:'push.../../../node_modules/tns-core-modules/data/observable/observable.js.Observable.notify', file:'file:///data/data/org.nativescript.client/files/app/vendor.js', line: 73988, column: 23
System.err: 	Frame: function:'notifyLaunch', file:'file:///data/data/org.nativescript.client/files/app/vendor.js', line: 91871, column: 17
System.err: 	Frame: function:'push.../../../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.client/files/app/vendor.js', line: 91804, column: 28
System.err: 	Frame: function:'push.../../../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.client/files/app/vendor.js', line: 91678, column: 14
System.err: 	Frame: function:'push.../../../node_modules/tns-core-modules/ui/frame/activity.js.NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.client/files/app/vendor.js', line: 89619, column: 25
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:983)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err: 	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
System.err: 	at android.app.Activity.performCreate(Activity.java:6975)
System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
System.err: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:105)
System.err: 	at android.os.Looper.loop(Looper.java:164)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

I am using the following configuration:
**Angular**: 7.1.1
**NativeScript CLI**: 5.0.2

Do I need to add any extra configuration to make AOT work?

Thanks!

**Comment by NathanWalker** [comment]
@benedictkhoo which command did you use to run with AoT? Just include full command here.

**Comment by benedictkhoo** [comment]
@NathanWalker  apologies, sure thing:
```
tns run android --emulator --bundle --hmr --env.aot
```

I added `--env.aot` to the default generated command

**Comment by NathanWalker** [comment]
@benedictkhoo Turns out this is related to `hmr`. At the moment you can't use `--env.aot` with `--hmr`. Just simply remove the `--hmr` option and AoT works fine 👍

**Comment by benedictkhoo** [comment]
Thanks @NathanWalker!
